{
  "id": "CVE-2022-42731",
  "references": [
    {
      "type": "exploit",
      "source": "NVD",
      "url": "https://github.com/mkalioby/django-mfa2/blob/0936ea253354dd95cb127f09d0efa31324caef27/mfa/FIDO2.py#L58",
      "time_stamp": "2022-10-11T19:05:00Z"
    }
  ]
}
